version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/inventory_db?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Anjana@3176
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Anjana@3176
      MYSQL_DATABASE: lol3
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
